In [3]:
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

/Users/Xivid/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/Xivid/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [4]:
print('Load training data...')
df_x_train = pd.read_csv('X_train.csv', header=0, index_col = 0)
df_y_train = pd.read_csv('y_train.csv', header=0, index_col = 0)

Load training data...


# Explore the dataset

In [5]:
df_x_train.head()

x0            x1            x2           x3          x4  \
id                                                                      
0.0  7077.537454  9.266811e+05  1.076365e+06  1029.624479  105.877440   
1.0  4406.423818  1.172821e+06  1.052467e+06  1000.548328  106.827932   
2.0  4460.878690  9.383663e+05  1.040878e+06  1096.946907  104.058397   
3.0  7152.388016  9.231857e+05  1.009414e+06  1044.520384  101.089811   
4.0  6531.930242  1.133718e+06  1.032579e+06  1032.803345  102.608707   

                x5           x6             x7             x8            x9  \
id                                                                            
0.0  180486.413011  1084.604810  296933.955135  104840.111208  10736.380544   
1.0  154325.607476  1034.480237  337446.411077  107789.409140  10502.289317   
2.0  197813.871177          NaN  373983.030405  109480.853246  10531.423706   
3.0  182569.308398          NaN  339951.730003  106597.409809  10070.560056   
4.0  200161.011648          NaN  332425.590129  107815.955426  10889.035954   

         ...               x877          x878           x879         x880  \
id       ...                                                                
0.0      ...       3.921803e+11  1.040522e+06 -437724.358877   957.470031   
1.0      ...       3.646601e+10  8.996629e+05 -486231.980813  1127.268384   
2.0      ...       9.147176e+10  9.575649e+05            NaN   976.904261   
3.0      ...       2.428226e+11           NaN -497230.891433   912.933479   
4.0      ...       1.273734e+11  1.059684e+06 -485361.519459  1001.804829   

             x881         x882        x883         x884          x885  \
id                                                                      
0.0  9.888772e+05  3830.501971   98.622927  1771.079992  10008.297422   
1.0  8.374596e+05  1981.239448   97.369765   843.078502  10046.004997   
2.0  9.210706e+05  2334.782218  113.751711  1134.021199  10307.683079   
3.0  1.117182e+06  3711.834265   98.080257  1553.015493  10952.963586   
4.0  9.523764e+05  3153.167755  100.671564  1271.047509  10048.902807   

             x886  
id                 
0.0  65052.593208  
1.0  65052.623467  
2.0           NaN  
3.0  65052.576387  
4.0  65052.535207  

[5 rows x 887 columns]

In [6]:
print("These columns are dummy!")
df_x_train[["x493", "x523", "x731", "x772"]]

These columns are dummy!


x493  x523  x731  x772
id                            
0.0      0.0   0.0   0.0   0.0
1.0      0.0   0.0   0.0   0.0
2.0      0.0   0.0   0.0   0.0
3.0      0.0   0.0   0.0   0.0
4.0      0.0   NaN   0.0   0.0
5.0      0.0   0.0   0.0   0.0
6.0      0.0   0.0   0.0   0.0
7.0      0.0   0.0   0.0   0.0
8.0      0.0   0.0   0.0   0.0
9.0      0.0   0.0   0.0   0.0
10.0     0.0   0.0   0.0   0.0
11.0     0.0   0.0   0.0   0.0
12.0     NaN   0.0   0.0   0.0
13.0     0.0   0.0   0.0   0.0
14.0     NaN   0.0   0.0   0.0
15.0     0.0   0.0   0.0   0.0
16.0     0.0   NaN   0.0   0.0
17.0     0.0   0.0   0.0   0.0
18.0     0.0   0.0   0.0   0.0
19.0     0.0   0.0   0.0   0.0
20.0     0.0   0.0   0.0   0.0
21.0     0.0   NaN   0.0   0.0
22.0     0.0   0.0   0.0   0.0
23.0     0.0   0.0   0.0   0.0
24.0     0.0   0.0   0.0   0.0
25.0     0.0   0.0   0.0   0.0
26.0     0.0   0.0   0.0   0.0
27.0     0.0   0.0   0.0   0.0
28.0     0.0   0.0   0.0   0.0
29.0     0.0   0.0   0.0   0.0
...      ...   ...   ...   ...
1182.0   0.0   0.0   0.0   0.0
1183.0   0.0   0.0   0.0   0.0
1184.0   0.0   0.0   0.0   0.0
1185.0   0.0   NaN   0.0   0.0
1186.0   0.0   0.0   0.0   0.0
1187.0   0.0   0.0   0.0   0.0
1188.0   0.0   0.0   0.0   0.0
1189.0   0.0   0.0   0.0   0.0
1190.0   0.0   0.0   0.0   0.0
1191.0   0.0   0.0   0.0   0.0
1192.0   0.0   0.0   0.0   0.0
1193.0   0.0   0.0   0.0   0.0
1194.0   NaN   0.0   0.0   0.0
1195.0   0.0   NaN   0.0   0.0
1196.0   0.0   0.0   0.0   0.0
1197.0   0.0   0.0   0.0   0.0
1198.0   0.0   0.0   0.0   0.0
1199.0   0.0   0.0   0.0   NaN
1200.0   0.0   0.0   0.0   0.0
1201.0   0.0   0.0   NaN   0.0
1202.0   NaN   0.0   0.0   0.0
1203.0   0.0   0.0   0.0   0.0
1204.0   0.0   0.0   0.0   0.0
1205.0   0.0   0.0   0.0   0.0
1206.0   0.0   0.0   0.0   0.0
1207.0   0.0   0.0   0.0   0.0
1208.0   0.0   0.0   0.0   0.0
1209.0   0.0   NaN   0.0   0.0
1210.0   0.0   0.0   0.0   0.0
1211.0   0.0   0.0   0.0   0.0

[1212 rows x 4 columns]

In [7]:
df_y_train.head()

y
id       
0.0  75.0
1.0  76.0
2.0  74.0
3.0  70.0
4.0  74.0

# Feature Selection

In [8]:
from numpy import isnan
def count_nan(l):
    return len([1 for x in l.values if isnan(x[0])])
print("number of nan's in each column:")
for col in df_x_train:
    print(col, count_nan(df_x_train[[col]]))

number of nan's in each column:
x0 90
x1 72
x2 80
x3 89
x4 79
x5 86
x6 71
x7 90
x8 90
x9 93
x10 85
x11 93
x12 78
x13 100
x14 92
x15 94
x16 77
x17 75
x18 91
x19 82
x20 89
x21 99
x22 96
x23 79
x24 85
x25 86
x26 82
x27 96
x28 87
x29 98
x30 95
x31 88
x32 78
x33 83
x34 91
x35 83
x36 104
x37 80
x38 77
x39 92
x40 92
x41 79
x42 79
x43 91
x44 79
x45 96
x46 90
x47 77
x48 72
x49 85
x50 98
x51 78
x52 82
x53 68
x54 78
x55 83
x56 78
x57 102
x58 69
x59 97
x60 76
x61 97
x62 84
x63 96
x64 97
x65 92
x66 72
x67 93
x68 95
x69 83
x70 76
x71 90
x72 83
x73 102
x74 91
x75 92
x76 100
x77 106
x78 81
x79 103
x80 93
x81 78
x82 85
x83 94
x84 82
x85 93
x86 98
x87 98
x88 86
x89 86
x90 85
x91 74
x92 80
x93 90
x94 66
x95 96
x96 83
x97 104
x98 87
x99 88
x100 76
x101 88
x102 84
x103 78
x104 79
x105 80
x106 81
x107 95
x108 98
x109 78
x110 89
x111 82
x112 85
x113 81
x114 113
x115 98
x116 92
x117 80
x118 89
x119 86
x120 77
x121 78
x122 100
x123 91
x124 90
x125 67
x126 83
x127 84
x128 93
x129 92
x130 83
x131 75
x132 101
x13

In [32]:
from scipy.stats import pearsonr
df_filled = df_x_train.fillna(df_x_train.mean()).copy()
features = df_filled.iloc[:,1:].columns.tolist()
labels = df_y_train["y"].values
correlations = {}
squares = {}
cubes = {}
for f in features:
    data_temp = df_filled[[f]]
    x1 = data_temp[f].values
    key = f
    correlations[key] = pearsonr(x1,labels)[0]
    squares[key] = pearsonr(x1*x1,labels)[0]
    cubes[key] = pearsonr(x1*x1*x1,labels)[0]
print("Correlations of each feature against age")
data_correlations = pd.DataFrame(correlations, index=['linear']).T
data_correlations = pd.concat([data_correlations, pd.DataFrame(squares, index=['square']).T], axis=1)
data_correlations = pd.concat([data_correlations, pd.DataFrame(cubes, index=['cube']).T], axis=1)
indices_desc = data_correlations['linear'].abs().sort_values(ascending=False).index
data_correlations.loc[indices_desc][(abs(data_correlations['linear']) >= 0.2) | (abs(data_correlations['square']) >= 0.2) | (abs(data_correlations['cube']) >= 0.2)]

/Users/Xivid/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:3003: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den


Correlations of each feature against age


/Users/Xivid/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:20: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


linear    square      cube
x746  0.455891  0.396818  0.316493
x82   0.451206  0.348666  0.243698
x685 -0.450200 -0.413561 -0.332616
x333  0.436991  0.360129  0.273646
x391  0.432717  0.345361  0.249282
x722  0.432330  0.327356  0.221739
x882 -0.429216 -0.410609 -0.370556
x751 -0.415688 -0.415738 -0.408910
x291 -0.409631 -0.407837 -0.398999
x96   0.408898  0.303164  0.229682
x349 -0.405713 -0.388604 -0.353431
x730 -0.376985 -0.349111 -0.306809
x687  0.367135  0.338791  0.297338
x363 -0.366201 -0.337772 -0.285545
x673 -0.364621 -0.322363 -0.258760
x340 -0.362479 -0.360407 -0.340910
x664  0.357290  0.200249  0.124964
x604 -0.354561 -0.351692 -0.344866
x185 -0.353596 -0.351442 -0.344607
x838 -0.345133 -0.342995 -0.336206
x300  0.340913  0.316890  0.282845
x180 -0.340528 -0.318360 -0.279760
x309 -0.340073 -0.340959 -0.337563
x665 -0.339921 -0.321952 -0.288244
x686 -0.336776 -0.334938 -0.329467
x608 -0.333330 -0.332871 -0.328751
x744 -0.332995 -0.328363 -0.320051
x297 -0.332164 -0.328658 -0.321256
x345 -0.327100 -0.326428 -0.321549
x853 -0.324018 -0.321294 -0.316660
...        ...       ...       ...
x870 -0.213791 -0.215235 -0.216073
x879  0.213640 -0.207377  0.180794
x795 -0.212368 -0.208146 -0.181978
x66  -0.212000 -0.205686 -0.178647
x198 -0.211618 -0.205589 -0.195433
x32  -0.211301 -0.203992 -0.176650
x457  0.211032 -0.202532  0.174871
x823  0.210943 -0.206877  0.181830
x611 -0.210838 -0.203821 -0.180202
x151 -0.210741 -0.198474 -0.162990
x781 -0.209662 -0.211641 -0.212681
x450 -0.209141 -0.204215 -0.195426
x697 -0.208444 -0.201223 -0.184388
x269  0.208393 -0.201310  0.174903
x277  0.207230 -0.194546  0.170348
x599 -0.207052 -0.196179 -0.175295
x209 -0.206626 -0.206350 -0.205261
x479  0.206514 -0.197008  0.168797
x844 -0.206421 -0.206024 -0.199529
x135 -0.206400 -0.205462 -0.197638
x374 -0.206000 -0.198887 -0.177620
x369 -0.203991 -0.192672 -0.169729
x336  0.202729 -0.195414  0.168342
x166 -0.202164 -0.192850 -0.177472
x428 -0.201807 -0.199167 -0.195782
x20  -0.201729 -0.189630 -0.167282
x283 -0.201577 -0.192703 -0.176291
x410 -0.201315 -0.191026 -0.169764
x365 -0.201115 -0.197863 -0.186636
x315 -0.201054 -0.184229 -0.157061

[149 rows x 3 columns]

In [34]:
selected_features = data_correlations.loc[(abs(data_correlations['linear']) >= 0.2) | (abs(data_correlations['square']) >= 0.2) | (abs(data_correlations['cube']) >= 0.2)].index
selected_features

Index(['x111', 'x120', 'x135', 'x137', 'x142', 'x151', 'x156', 'x158', 'x166',
       'x180',
       ...
       'x85', 'x853', 'x870', 'x871', 'x879', 'x88', 'x882', 'x89', 'x94',
       'x96'],
      dtype='object', length=149)

# Training SVM

In [35]:
from sklearn import svm

In [36]:
df_filled = df_x_train.fillna(df_x_train.mean())
X = df_filled[selected_features].values
X

array([[1.95976133e+00, 2.16936541e+00, 9.29232320e+02, ...,
        4.84234722e+03, 7.32607710e+03, 2.57405227e+03],
       [1.71727571e+00, 2.07239942e+00, 7.23192440e+02, ...,
        5.87845951e+03, 5.18107709e+03, 3.47193075e+04],
       [1.84589903e+00, 2.12845633e+00, 9.72114889e+02, ...,
        5.63605450e+03, 7.07301317e+03, 6.02618178e+03],
       ...,
       [1.93856748e+00, 2.01882280e+00, 6.52501589e+02, ...,
        5.55314778e+03, 8.64103835e+03, 2.53911047e+04],
       [1.71181534e+00, 2.27642177e+00, 6.72780680e+02, ...,
        6.29702403e+03, 9.16006350e+03, 6.41636835e+03],
       [1.82235941e+00, 2.14873057e+00, 9.19117362e+02, ...,
        5.77003229e+03, 6.45802195e+03, 3.77187226e+03]])

In [37]:
y = df_y_train['y'].values
y

array([75., 76., 74., ..., 78., 78., 56.])

In [44]:
print('Splitting into training and validation dataset')
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2) # , random_state = 19960503)

Splitting into training and validation dataset


In [45]:
clf = svm.SVR()
clf.fit(X_train, y_train)
y_val_p = clf.predict(X_val)    
result = r2_score(y_val, y_val_p)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

# Predict and output submission

In [47]:
print('Load testing data...')
df_x_test = pd.read_csv('X_test.csv', header=0, index_col = 0)
df_x_test = df_x_test.fillna(df_x_train.mean())
X_test = df_x_test[selected_features].values
# print(X_test)
y_pred = clf.predict(X_test)
y_pred


Load testing data...


array([70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04146341,
       70.04146341, 70.04146341, 70.04146341, 70.04146341, 70.04

In [255]:
f = open("submission.csv", "w")
f.write("id,y\n")
for i,x in enumerate(y_pred):
    f.write("{},{}\n".format(i,x))
f.close()

# Randomly find best result

In [ ]:
best = 0
for i in range(100):
    print('Splitting into training and validation dataset')
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.15) # , random_state = 19960503)
    # create dataset for lightgbm
    lgb_train = lgb.Dataset(X_train, y_train)
    lgb_eval = lgb.Dataset(X_val, y_val, reference=lgb_train)
    # specify your configurations as a dict
    params = {
        'task': 'train',
        'boosting_type': 'gbdt',
        'objective': 'regression',
        #'metric': {'l1', 'l2'},
        'num_leaves': 31,
        'learning_rate': 0.05,
        'feature_fraction': 0.5,
        'bagging_fraction': 0.8,
        'bagging_freq': 5,
        'verbose': 0
    }

    def custom_r2(preds, train_data):
        labels = train_data.get_label()
        return 'r2', r2_score(labels, preds), True

    print('Start training...')
    # train
    gbm = lgb.train(params,
                    lgb_train,
                    num_boost_round=500,
                    feval=custom_r2,
                    valid_sets={lgb_train, lgb_eval},
                    early_stopping_rounds=20)
    y_val_p = gbm.predict(X_val, num_iteration=gbm.best_iteration)
    
    result = r2_score(y_val, y_val_p)
    if result > best:
        print("New Best {}".format(result))
        best = result
        y_pred = gbm.predict(X_test, num_iteration=gbm.best_iteration)
        f = open("submission{0:.4f}.csv".format(best), "w")
        f.write("id,y\n")
        for i,x in enumerate(y_pred):
            f.write("{},{}\n".format(i,x))
        f.close()